language: rust
sudo: false
rust:
 - stable
 - nightly
script:
 - touch harfbuzz-sys/harfbuzz/{configure.ac,aclocal.m4,configure,Makefile.am,Makefile.in}
 - cargo build --verbose --manifest-path=harfbuzz-sys/Cargo.toml
 - cargo build --verbose --manifestpath=harfbuzz/Cargo.toml
