[package]
name = "harfbuzz-sys"
version = "0.3.1"

authors = ["The Servo Project Developers"]
license = "MIT"

description = "Rust bindings to the HarfBuzz text shaping engine"
repository = "https://github.com/servo/rust-harfbuzz"
documentation = "https://docs.rs/harfbuzz-sys/"
keywords = ["opentype", "font", "text", "layout", "unicode"]
categories = ["external-ffi-bindings", "internationalization"]

exclude = [
    "harfbuzz/test/*"
]
include = [
    "**/Makefile.in"
]

links = "harfbuzz"
build = "build.rs"

[build-dependencies]
pkg-config = { version = "0.3", optional = true }
cmake = { version = "0.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.17"
core-text = "13"
foreign-types = "0.3"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = { version = "0.4", default-features = false }

[features]
default = ["build-native-harfbuzz", "build-native-freetype"]
build-native-harfbuzz = ["cmake", "pkg-config"]
build-native-freetype = ["freetype/servo-freetype-sys"]
